contigua:
	gcc -c lista_contigua.c -o lista_contigua
	gcc main.c lista_contigua.o -o main
	./main
encadeada:
	gcc -c lista_encadeada.c -o lista_encadeada
	gcc main.c lista_encadeada.o -o main
	./main
encadeada-dupla:
	gcc -c lista_encadeada_dupla.c -o lista_encadeada_dupla
	gcc main.c lista_encadeada_dupla.o -o main
	./main