contigua:
	gcc -c lista_contigua.c -o lista_contigua.o
	gcc main.c lista_contigua.o -o main
	./main
encadeada:
	gcc -c lista_encadeada.c -o lista_encadeada.o
	gcc main.c lista_encadeada.o -o main
	./main
encadeada-dupla:
	gcc -c lista_encadeada_dupla.c -o lista_encadeada_dupla.o
	gcc main.c lista_encadeada_dupla.o -o main
	./main
encadeada-sentinela:
	gcc -c lista_encadeada_sentinela.c -o lista_encadeada_sentinela.o
	gcc main.c lista_encadeada_sentinela.o -o main
	./main